FROM node:16.19.0-alpine

WORKDIR /app

COPY ./package.json .

#RUN npm config set unsafe-perm true
#RUN mkdir node_modules

#RUN chmod -R 777 node_modules

RUN npm install 

#RUN chown -R usairam /app/node_modules

#USER usairam
#RUN mkdir '/app/node_modules/.cache' 

# && chmod -R 777 '/app/node_modules/.cache'

COPY . .

CMD ["npm", "run", "start"]